theme: jekyll-theme-primer
name: "./c4d"
title: null
description: ""
# image: "https://vsky.space/content/cover/c4d.jpg"

# twitter:
#   card: "summary_large_image"
#   title: "vsky.space/c4d"
#   description: "Scripts & Projects for Cinema 4D"
#   image: "https://vsky.space/content/cover/c4d.jpg"
#   username: "AleksandrovskyV"
#   site: "@AleksandrovskyV"