name: Deploy GitHub Pages without Jekyll Trash

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Build Clean HTML
        run: |
          # 1. Сборка главного index.html из корневого README.md
          echo '<!DOCTYPE html><html lang="en-US"><head><meta charset="UTF-8">' > index.html
          echo '<meta name="viewport" content="width=device-width, initial-scale=1">' >> index.html
          echo '<title>/c4d</title>' >> index.html
          echo '<meta name="description" content="Scripts & Projects for Cinema 4D">' >> index.html
          echo '<meta property="og:title" content="/c4d">' >> index.html
          echo '<meta property="og:description" content="Scripts & Projects for Cinema 4D">' >> index.html
          echo '<link rel="stylesheet" href="./assets/css/style.css">' >> index.html
          echo '</head><body><div class="container-lg px-3 my-5 markdown-body">' >> index.html
          
          # Конвертируем корень
          tr -d '\r' < README.md | pandoc -f markdown-yaml_metadata_block -t html | sed 's/\.md"/\.html"/g' >> index.html
          
          echo '</div></body></html>' >> index.html

          # 2. Сборка всех .md файлов внутри папки readme
          if [ -d "readme" ]; then
            shopt -s nocaseglob
            
            for file in readme/*.md; do
              [ -e "$file" ] || continue
              
              base_name=$(basename "$file")
              filename="${base_name%.*}"
              html_file="readme/${filename}.html"
              
              # Для вложенных страниц title будет "/имя_файла" и правильный путь к CSS через "../"
              echo "<!DOCTYPE html><html lang=\"en-US\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>/$filename</title><link rel=\"stylesheet\" href=\"../assets/css/style.css\"></head><body><div class=\"container-lg px-3 my-5 markdown-body\">" > "$html_file"
              
              pandoc -f markdown-yaml_metadata_block -t html "$file" | tr -d '\r' | sed 's/\.md"/\.html"/g' >> "$html_file"
              
              echo '</div></body></html>' >> "$html_file"
            done
            
            shopt -u nocaseglob
          fi



      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
